Continue transformation on JSON parse error
snowplow-archive/snowplow-snowflake-loader pull request #79
Opened 2019-02-12 09:46 UTC by nov1n

## Rationale
The loader throws an uncaught [`RuntimeException`](https://github.com/snowplow-incubator/snowplow-snowflake-loader/blob/a069f916171a971f551ba8d48e24d7c083588b50/transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/Transformer.scala#L61) when encountering an invalid line in the input TSV file. This means any upstream enrichments that corrupt a line will cause the entire batch to fail. This PR instead skips invalid lines and collects them to optionally be written to a separate `errorEvents` bucket on S3.

## Changes include
* Lines containing JSON parse errors that do not impact shredding are skipped. An example of this error is: `Context JSON did not contain a stringly typed schema field`.
* Events (lines) that fail to be parsed are logged to stdout including line number, filename, reason, and line contents.
* An optional configuration `badEventsUrl` parameter is added of type `Option[S3Folder]`. If the parameter is set, error events will be written to a file in this bucket. The filename is identical to the source filename from which the event originated.

## Notes
* The implementation uses `wholeTextFile` instead of `textFile`. This means large files are no longer split into 32MB chunks and paralellized, but this should not be a problem because files do not tend to be this large.
* If mandatory Snowplow fields are missing, this will cause an error in the shredding process we cannot recover from. This is not a problem because this error should never occur and something is seriously wrong upstream if it does.

## Todo
* I added a custom [serializer](https://github.com/PicnicSupermarket/snowplow-snowflake-loader/pull/1/files#diff-5c851a8fdd47dff2dd3f65b5322c13aaR327) for `Option[S3Config]`. I feel like it should be possible to reuse the one for `S3Config`, but I couldn't get it to work.
* Add an optional `errorEventsUrl` field to schema and bump version to `com.snowplowanalytics.snowplow.storage/snowflake_config/jsonschema/1-0-2`, see [Proposed Schema Changes](#proposed-schema-changes).
* Fix failing configuration spec test by changing schema version to 1-0-2.

### Proposed schema changes
This is what the proposed new schema looks like. It adds an optional field `errorEventsUrl` of type `string` and format `uri`:

```
{
  "" : "http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#",
  "description" : "Snowplow Snowflake storage configuration",
  "self" : {
    "vendor" : "com.snowplowanalytics.snowplow.storage",
    "name" : "snowflake_config",
    "format" : "jsonschema",
    "version" : "1-0-2"
  },
  "type" : "object",
  "properties" : {
    "name" : {
      "type" : "string"
    },
    "auth" : {
      "description" : "Authentication method for Snowflake Load",
      "oneOf" : [ {
        "type" : "object",
        "properties" : {
          "accessKeyId" : {
            "type" : "string"
          },
          "secretAccessKey" : {
            "type" : "string"
          }
        },
        "required" : [ "accessKeyId", "secretAccessKey" ]
      }, {
        "type" : "object",
        "properties" : {
          "roleArn" : {
            "type" : [ "string", "null" ],
            "minLength" : 20
          },
          "sessionDuration" : {
            "type" : "integer",
            "minimum" : 900
          }
        },
        "required" : [ "roleArn", "sessionDuration" ]
      }, {
        "type" : "null"
      } ]
    },
    "awsRegion" : {
      "type" : "string"
    },
    "manifest" : {
      "type" : "string"
    },
    "snowflakeRegion" : {
      "type" : "string"
    },
    "database" : {
      "type" : "string"
    },
    "account" : {
      "type" : "string"
    },
    "warehouse" : {
      "type" : "string"
    },
    "schema" : {
      "type" : "string"
    },
    "input" : {
      "type" : "string",
      "format" : "uri"
    },
    "stage" : {
      "type" : "string"
    },
    "stageUrl" : {
      "type" : "string",
      "format" : "uri"
    },
    "errorEventsUrl" : {
      "type" : "string",
      "format" : "uri"
    },
    "username" : {
      "type" : "string"
    },
    "password" : {
      "type" : [ "string", "object" ],
      "properties" : {
        "ec2ParameterStore" : {
          "type" : "object",
          "properties" : {
            "parameterName" : {
              "type" : "string"
            }
          },
          "required" : [ "parameterName" ]
        }
      },
      "required" : [ "ec2ParameterStore" ]
    },
    "maxError" : {
      "type" : "integer"
    },
    "jdbcHost" : {
      "type" : "string"
    },
    "id" : {
      "type" : "string",
      "format" : "uuid"
    },
    "purpose" : {
      "type" : "string",
      "enum" : [ "ENRICHED_EVENTS" ]
    }
  },
  "additionalProperties" : false,
  "required" : [ "name", "auth", "awsRegion", "manifest", "snowflakeRegion", "database", "account", "warehouse", "input", "stage", "stageUrl", "username", "password", "purpose" ]
}
```

2019-02-12 09:57 UTC, snowplowcla commented
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

2019-02-13 10:47 UTC, nov1n commented
I signed it.

2019-02-13 10:50 UTC, snowplowcla commented
Confirmed! @nov1n  has signed the Individual Contributor License Agreement. Thanks so much

2019-02-13 16:23 UTC, rzats requested changes

2019-02-13 16:23 UTC, rzats commented on core/src/main/scala/com.snowplowanalytics.snowflake.core/Config.scala
> +  object optionalS3FolderSerializer extends CustomSerializer[Option[S3Folder]]((formats) =>
This serializer is unnecessary and in fact breaks JSON parsing - if `errorEventsUrl` is missing, any further optional fields are also [rendered as `None` even if they *are* present and correct](https://travis-ci.org/snowplow-incubator/snowplow-snowflake-loader/builds/492072506#L752-L754).

2019-02-13 16:23 UTC, rzats commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/TransformerJob.scala
> +  val LOG = LoggerFactory.getLogger(TransformerJob.getClass)
This is inconsistent with other logging in the transformer that does not use slf4j. I'd switch to simple `println`.

2019-02-13 16:23 UTC, rzats commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/TransformerJob.scala
> +        fileContents.lines.zipWithIndex.map{case (event, index) =>
`zipWithIndex` isn't a great idea - it loads an entire file into a single node's memory, which is a no-no when working with Spark. As far as I can tell the only reason to do this is to have slightly more verbose logging output, so I'd not use this function at all.

2019-02-13 16:23 UTC, rzats commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/TransformerJob.scala
> -
Unnecessary whitespace edits here.

2019-02-14 05:03 UTC, chuwy reviewed
Hi @nov1n! I definitely like the idea! I think right now Snowflake Loader is overly optimistic about its input (although it never was a problem in our experience).

However, I think Spark provides more optimal solutions for this kind of dataset splitting, e.g. you can get some inspiration from RDB Shredder: https://github.com/snowplow/snowplow-rdb-loader/blob/master/shredder/src/main/scala/com.snowplowanalytics.snowplow.storage/spark/ShredJob.scala#L405-L422

Also please pay attention that our 0.5.0 version [will be using](https://github.com/snowplow-incubator/snowplow-snowflake-loader/pull/74) Scala Analytics SDK 0.4.0, which has much better API.

Thank you very much for raising this!

2019-02-14 05:03 UTC, chuwy commented on core/src/main/scala/com.snowplowanalytics.snowflake.core/Config.scala
> +  errorEventsUrl: Option[Config.S3Folder],
I'd rename this to something like `badBucket` to be aligned with Spark enrich and RDB Shredder.

2019-02-14 05:03 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/TransformerJob.scala
> +              LOG.error(s"""Could not parse event on line $lineNumber in file $fileName
In case for some reasons we have a lot of bad events - we'll get a multi-GB log file.

2019-02-14 12:38 UTC, nov1n commented
> Hi @nov1n! I definitely like the idea! I think right now Snowflake Loader is overly optimistic about its input (although it never was a problem in our experience).
> 
> However, I think Spark provides more optimal solutions for this kind of dataset splitting, e.g. you can get some inspiration from RDB Shredder: https://github.com/snowplow/snowplow-rdb-loader/blob/master/shredder/src/main/scala/com.snowplowanalytics.snowplow.storage/spark/ShredJob.scala#L405-L422
> 
> Also please pay attention that our 0.5.0 version [will be using](https://github.com/snowplow-incubator/snowplow-snowflake-loader/pull/74) Scala Analytics SDK 0.4.0, which has much better API.
> 
> Thank you very much for raising this!

Thanks for the quick feedback. The problem addressed by this PR however is very pressing for us, and we're looking for a solution. Will you merge and release this in the near future if I address the feedback, or should I run a custom binary to get this functionality?

2019-02-27 09:47 UTC, nov1n commented
@chuwy could you get back to my question?

2019-02-27 15:47 UTC, chuwy commented
Hi @nov1n! Sorry, missed your last question. Couple of points here:

1. We're definitely interested in implementing bad rows for Snowflake Loader and we'll merge this feature if it will match criterions outlined below
2. No performance penalty. Its quite easy to run into skewing issues if you try to split streams (e.g. on two nodes cluster, one node writes 99% of good data and another 1% of bad data, so we're wasting 50% of cluster). If it is not possible to avoid that, we should at least make it optional (I don't think we ever stumbled upon invalid enriched data in transformer)
3. It should be based on top of ongoing 0.5.0 branch https://github.com/snowplow-incubator/snowplow-snowflake-loader/pull/74 as we changed several underlying libs significantly

Thanks!

2019-02-28 10:54 UTC, nov1n commented on core/src/main/scala/com.snowplowanalytics.snowflake.core/Config.scala
> +  object optionalS3FolderSerializer extends CustomSerializer[Option[S3Folder]]((formats) =>
I thought the same, but if I remove it I get a runtime exception [here](https://github.com/snowplow-incubator/snowplow-snowflake-loader/pull/79/files#diff-d9163363ee232782ef2656a544f5d41dR29): 
```
Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to com.snowplowanalytics.snowflake.core.Config$S3Folder
	at com.snowplowanalytics.snowflake.transformer.TransformerJobConfig.errorOutput(TransformerJobConfig.scala:30)
```
It seems that at runtime it is a `String`, even though the compiler thinks it will be an `S3Folder`. Am I missing something?

2019-08-28 09:40 UTC, chuwy commented
Closing as this has been implemented as part of https://github.com/snowplow-incubator/snowplow-snowflake-loader/issues/85

2019-08-28 09:40 UTC, closed without merging