Bad row
snowplow-archive/snowplow-snowflake-loader pull request #86
Opened 2019-06-10 21:46 UTC by aldemirenes

2019-06-11 06:54 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/BadRow.scala
> +package com.snowplowanalytics.snowflake.transformer
Don't forget about license header https://github.com/snowplow-incubator/snowplow-snowflake-loader/blob/master/core/src/main/scala/com.snowplowanalytics.snowflake.core/Config.scala#L1-L12

2019-06-11 07:22 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/BadRow.scala
> +
There's a convention to put ADT members inside an object:

```
sealed trait Something
object Something {
  case class Foo(foo: Int) extends Something
  case object Bar extends Something
}
```

2019-06-11 07:22 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/BadRow.scala
> +final case class GenericBadRow(
Can you add some description for these classes and members?

2019-06-11 07:22 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/BadRow.scala
> +  schemaKey: SchemaKey = SchemaKey(
I don't think this parameter needs to be changeable. E.g. if user wants to new property - he/she still stuck with this case class. So case class can have only one `schemaKey`

2019-06-11 07:22 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/BadRow.scala
> +  failure: String,
I think failure needs to directly represent error from Analytics SDK. So structure would something like this:

1. `data` - original row, added by transformer, invalidated by SDK
2. `failure` - details about SDK error
3. `processor` - just a metadata about transformer

2019-06-11 07:22 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/BadRow.scala
> +  val default = Processor("snowplow-snowflake-loader", "0.0.0")
I think you can get this from build confgiuration. Have a look at `Main.scala`

2019-06-11 07:22 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/BadRow.scala
> +final case class InvalidTimestamp(timestamp: Instant, timestampType: TimestampType) extends SnowflakeFailure
What if we assume `Map`-like structure:

```
Map[Property, NonEmptyList[Failure]]
```

Where `Failure` can be `InvalidTimestamp` (without hardcoded `TimestampType`) and adding new types of validations for other fields will be much easier.

2019-06-11 07:30 UTC, aldemirenes commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/BadRow.scala
> +  failure: String,
Also, what do you think about the types of `failure` and `data`? I want to give them type different than `String` however I could not do it because `Event.parse()` returning `String` as an error and `data` is always `String` I guess.

2019-06-13 09:59 UTC, chuwy reviewed
This is getting along very well! Did you already have a chance to run it locally or on EMR?

2019-06-13 09:59 UTC, chuwy commented on project/Dependencies.scala
> +  val circeLiteral     = "io.circe"              %% "circe-literal"                % V.circe
Can we add it to test scope only? `... % "test"`

2019-06-13 09:59 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/BadRow.scala
> +sealed trait FailureInfo
Don't forget docstrings - they help everyone following your reasoning.

2019-06-13 09:59 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/BadRow.scala
> +sealed trait FailureInfo
There's a strong convention in Java/Scala world to have only one top-level entity per file. E.g. if you create `Foo.scala`, it should have only `class/trait Foo` and `and `object Foo`. Thus, could you please move `FailureInfo` either to its own file or inside `BadRow` object (which is probably preferable).

2019-06-13 09:59 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/SnowflakeErrorCheck.scala
> +  // TODO Enes: check whether timestamp related problem of Snowflake is occuring due to
Yep, that's a good point. I'm not sure what is acceptable range they have. Maybe @colmsnowplow encountered Snowflake's allowed datetime ranges?

2019-06-13 09:59 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/SnowflakeErrorCheck.scala
> +    timestamp.filter(ts => ts.getEpochSecond < 0).map(ts => ValueError(ts.toString.asJson, column, "Invalid timestamp"))
Let's change `Invalid timestamp` to something like `Timestamp is out of Snowflake range` as technically it is valid.

2019-06-13 09:59 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/SnowflakeErrorCheck.scala
> +    timestamp.filter(ts => ts.getEpochSecond < 0).map(ts => ValueError(ts.toString.asJson, column, "Invalid timestamp"))
Just an FP nit: `filter + map` can be replaced with `flatMap`

2019-06-13 09:59 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/Transformer.scala
> +          case e: ProvisionedThroughputExceededException =>
Let's make it a bad row actually. It's extremely rare these days and we'd rather recover it from bad rows rather than kill whole pipeline? Is it the case in RDB Shredder as well?

2019-06-13 09:59 UTC, chuwy commented on transformer/src/test/scala/com/snowplowanalytics/snowflake/transformer/bad/NotEnrichedEventsSpec.scala
> +    "NOT AN ENRICHED EVENT",
Can you create a ticket in Analytics SDK, something like "Add specific error for non-tsv lines"?

2019-06-13 09:59 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/TransformerJob.scala
> +    val common = input
Cannot we unify `input` and `common` into `val input = sc.textFile(jobConfig.input).textFile(jobConfig.input)`?

2019-06-13 09:59 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/TransformerJobConfig.scala
> +case class S3Config(enrichedArchive: S3Folder, snowflakeOutput: S3Folder, runId: String) extends TransformerJobConfig {
Don't forget about `sealed trait`/`object` convention. All members should be inside an object.

2019-06-13 09:59 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/TransformerJob.scala
> +    val snowflakeErrorCheckRes = withoutParsingFailure
It's little bit sad to see how bad rows overcomplicated this extremely simple job. Make a note to run a benchmark for both previous and current version against same data (which I'll provide you later)

2019-06-13 09:59 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/TransformerJobConfig.scala
> +case class FSConfig(input: String, goodOutput: String, badOutput: String) extends TransformerJobConfig {
Is this test-only?

2019-06-13 09:59 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/TransformerJobConfig.scala
> +  // TODO Enes: take folder for badOutput as an argument and return it with suitable format in here
Snowflake is configured through self-describing JSON, so you'll need to add bad rows into a new (2-0-0, I suppose) schema: https://github.com/snowplow/iglu-central/tree/master/schemas/com.snowplowanalytics.snowplow.storage/snowflake_config/jsonschema

2019-06-13 09:59 UTC, chuwy commented on project/Dependencies.scala
> +  val circeCore        = "io.circe"              %% "circe-core"                   % V.circe
Isn't circe core a transitive dependency of Analytics SDK (though version can be a little bit old)?

2019-06-13 10:33 UTC, aldemirenes commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/Transformer.scala
> +          case e: ProvisionedThroughputExceededException =>
I should create a new type of failure which is named `ProvisionedThroughputExceeded` like a `DeduplicationError` then ?
Also, exception is thrown in the RDB shredder in this case too. I can open a ticket for this issue if you want.

2019-06-13 10:39 UTC, aldemirenes commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/TransformerJobConfig.scala
> +case class FSConfig(input: String, goodOutput: String, badOutput: String) extends TransformerJobConfig {
Yep, it is test only. Do you think there is a problem with it ?

2019-06-13 10:44 UTC, aldemirenes commented on project/Dependencies.scala
> +  val circeCore        = "io.circe"              %% "circe-core"                   % V.circe
Yep, I added it in order to use the new version of circe. Is there a problem ? I think I should exclude it from Analytics SDK in order to not to encounter with any binary incompatibility problem ?

2019-06-13 10:46 UTC, colmsnowplow commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/SnowflakeErrorCheck.scala
> +  // TODO Enes: check whether timestamp related problem of Snowflake is occuring due to
@chuwy what are we referring to with 'timestamp related problem of Snowflake?'

2019-06-13 14:28 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/SnowflakeErrorCheck.scala
> +  // TODO Enes: check whether timestamp related problem of Snowflake is occuring due to
@colmsnowplow the recent issue we had with a client, where they had an event with negative timestamp, which couldn't be loaded into a Snowflake, so somebody had to remove it manually from S3. By any chance, are you aware if there's known time range that can be accepted? Or maybe other similar problems where DB rejects the row (we had it with too long lines, but fixed it in 0.4.2).

2019-06-13 14:30 UTC, chuwy commented on project/Dependencies.scala
> +  val circeCore        = "io.circe"              %% "circe-core"                   % V.circe
There's no guarantees that 0.x version maintain a binary compatiblity. Although, circe is used to be very good in that regard and I don't know of any breakages since 0.9.0. You certainly shouldn't have to exclude it from SDK.

> I added it in order to use the new version of circe. Is there a problem ? 

No, no problem at all - just wanted to make sure its not a duplicate.

2019-06-13 14:32 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/TransformerJobConfig.scala
> +case class FSConfig(input: String, goodOutput: String, badOutput: String) extends TransformerJobConfig {
No quite otherwise. I think it's the problem that we cannot run it locally with current configuration. If its _very easy to do_ - feel free to make FS working in final asset.

2019-06-13 15:12 UTC, aldemirenes commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/TransformerJobConfig.scala
> +case class FSConfig(input: String, goodOutput: String, badOutput: String) extends TransformerJobConfig {
I will look into it to find out if I can.

2019-06-13 17:23 UTC, colmsnowplow commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/SnowflakeErrorCheck.scala
> +  // TODO Enes: check whether timestamp related problem of Snowflake is occuring due to
Oh yes - apologies, I should have joined the dots there.

Sorry, I don't know the range, [the docs specify it for time values](https://docs.snowflake.net/manuals/sql-reference/data-types-datetime.html#time) but not timestamp values.

2019-06-13 18:37 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/SnowflakeErrorCheck.scala
> +  // TODO Enes: check whether timestamp related problem of Snowflake is occuring due to
Thanks, Colm. @aldemirenes, I think the only option we have then is to test our assumption when we'll be testing loading. Could you please set a reminder for yourself to create fake odd timestamps in the enriched data?

2019-06-14 07:14 UTC, aldemirenes commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/TransformerJobConfig.scala
> +  // TODO Enes: take folder for badOutput as an argument and return it with suitable format in here
Should I open a new PR for it or continue to work on it in the current PR related with the Snowflake bad-row schema in iglu-central ?

2019-06-14 08:21 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/TransformerJobConfig.scala
> +  // TODO Enes: take folder for badOutput as an argument and return it with suitable format in here
I think it can go with same PR as evertyhig there is related to a new release. Just separate commit.

2019-06-19 15:22 UTC, chuwy requested changes
Looks good! Just making rows actually self-describing is a crucial part.

2019-06-19 15:22 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/BadRow.scala
> +  case class ParsingFailure(original: String, errors: NonEmptyList[String]) extends BadRow
Let's make it `final`

2019-06-19 15:22 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/BadRow.scala
> +  sealed trait Failure
I agree that types are quite descriptive here, but still ScalaDoc is welcome!

2019-06-19 15:22 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/TransformerJob.scala
> +      .map { badRow => Row(badRow.asJson.noSpaces) }
The big thing I overlooked is that we're not making these bad rows self-describing. All bad rows need to bear their associated schemas.

2019-06-20 07:28 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/BadRow.scala
> +      SelfDescribingData(LoaderFailureWithUnknownData, this.asInstanceOf[BadRow].asJson)
Never use `asInstanceOf` in Scala - its very unsafe method. If object will turn out to be not a subclass of the type you want to cast it to - it will compile without warning, but fail in runtime. Instead `(this: BadRow).asJson` can be used.

2019-06-20 07:30 UTC, chuwy commented on transformer/src/main/scala/com/snowplowanalytics/snowflake/transformer/BadRow.scala
> +  def toCompactJson: String  = getSelfDescribingData.asString
Can you try `asJson.noSpaces` here? We should have an implicit `Encoder[SelfDescribingData[Json]]` somewhere. Either in `com.snowplowanalytics.iglu.core.circe.implicits` or in `com.snowplowanalytics.iglu.core.circe.CirceCodecs` (or similar package, don't remember exact name)

2019-06-20 07:32 UTC, chuwy commented on core/src/main/scala/com.snowplowanalytics.snowflake.core/BadRowSchemas.scala
> +object BadRowSchemas {
👍

2019-06-21 14:42 UTC, chuwy approved these changes
Looks awesome!

2019-06-21 14:42 UTC, chuwy commented on transformer/src/test/scala/com/snowplowanalytics/snowflake/transformer/bad/BadRowSchemaValidationSpec.scala
> +          resolver <- Resolver.parse(parse(BadRowSchemaValidationSpec.resolverConfig)).toEither
This resolver is used without changes in both tests - you can initialize it once and reuse.

2019-06-21 14:42 UTC, chuwy commented on transformer/src/test/scala/com/snowplowanalytics/snowflake/transformer/bad/BadRowSchemaValidationSpec.scala
> +        res.isRight mustEqual true
`res must beRight`

2019-06-21 14:42 UTC, chuwy commented on transformer/src/test/scala/com/snowplowanalytics/snowflake/transformer/bad/BadRowSchemaValidationSpec.scala
> +          resolver <- Resolver.parse(parse(BadRowSchemaValidationSpec.resolverConfig)).toEither
Also, you don't even need it as `Either`, so you can unwrap it right there `.valueOr(_ => throw new RuntimeException("Test resolver is invalid"))`

2019-06-21 14:42 UTC, chuwy commented on transformer/src/test/scala/com/snowplowanalytics/snowflake/transformer/bad/BadRowSchemaValidationSpec.scala
> +        res.leftMap(e => println(e)).isRight mustEqual true
Don't forget to remove this `println`.

2019-06-21 14:42 UTC, chuwy commented on core/src/test/scala/com/snowplowanalytics/snowflake/core/ConfigSpec.scala
> +class ConfigSpec extends Specification {
Could you please fix the formatting:

```
... Specification { def is = s2"""
    Parse valid setup configuration $e1
    Parse valid load configuration $e2
    ...
}
```

2019-08-28 09:41 UTC, merged